### ISSUE TITLE
Tracking issue for libtest JSON output

### ISSUE THREAD

**Issue by sunshowers** [nextest-rs/nextest#1152]
- **Initial implementation:** #1086
- **Nextest version:** 0.9.65 and above
- **Enable with:** Set `NEXTEST_EXPERIMENTAL_LIBTEST_JSON=1` in the environment

Still to do before stabilizing the format:

- [ ] Include stderr and stdout for failing tests (#1088)
- [ ] Figure out situation around splitting vs combining stdout and stderr (may need to provide a little command-line configuration for this, e.g. `--message-format-version 0.1,test-output=split`)
- [ ] Provide deserializers for the format in nextest-metadata
- [ ] Switch integration tests over to this format (the ones in `integration-tests/` scrape the current, unstable format, which sucks
- [ ] Include messages for start-of-test-run and end-of-test-run (maybe only under the `libtest-json-plus` variant)
- [ ] Write documentation
- [ ] Get real-world use and feedback
