### ISSUE TITLE
Tracking feature for setup-scripts

### ISSUE THREAD

**Issue by sunshowers** [nextest-rs/nextest#978]
# Open questions

- [ ] How do we support build archive/reuse with Cargo commands?
- [ ] Is the current format for environment variables (KEY=value) okay? Do we need to check that KEY/value are unique identifiers?
- [ ] Should we have a special syntax for running Cargo binaries?

**Comment by tisonkun** [comment]
This setup script seems to be executed before test. How can I do if I'd set up a database and teardown after the test suite finished?

For non-blocking start, I may use `&` to keep the database running in the background. But it seems missing a teardown script hook.

**Comment by sunshowers** [comment]
@tisonkun correct, there is no support for teardown scripts yet (at work, we use setup scripts to pre-seed and write out a database as a tarball to disk, which tests can then pick up). But it's something that would definitely be nice to have.

**Comment by tlater-famedly** [comment]
It would be nice if there was a way to either access `$NEXTEST_PROFILE` in the setup scripts, *or* override the setup scripts from the default profile.

Currently, it's difficult to set up a different set of things in my CI profile, which is annoying as I'm trying to set up docker containers which have to use different volume paths on CI hosts. I can rely on the fact that the scripts seem to be executed in order, at least, but it feels hacky to rely on that and is hard to express in code.

It would be much nicer if I could change script behavior slightly depending on profile, or just execute different scripts in different profiles altogether.

**Comment by sunshowers** [comment]
@tlater-famedly Yeah that's a good idea, I think we should uniformly set NEXTEST_PROFILE in test and script environments.

**Comment by sunshowers** [comment]
@tlater-famedly this is now set in nextest 0.9.89, which was just released.

**Comment by sunshowers** [comment]
As of nextest 0.9.98, [setup scripts](https://nexte.st/docs/configuration/setup-scripts) now use the `[scripts.setup]` configuration. The location of the configuration has been changed to support the new [wrapper scripts](https://nexte.st/docs/configuration/wrapper-scripts/).

The old `[script.*]` location will work for a short while, but will be removed in the near future. (This is not a breaking change because setup scripts aren't stable yet... though hopefully soon!)

**Comment by metatoaster** [comment]
Would the ability to provide environment variables specific to a given script be a welcomed addition?  As an example, given some `cargo` tool (or any other script/binary), it might accept specific environment variables to alter how it behaves or what it does, and naturally it would be nice to be able to define it in the setup script definition. As an example, the `.config/nextest.toml` could be defined like:

```toml
[scripts.setup.mode_a]
command = ["cargo", "tool", "run"]
env = {
    TOOL_MODE = "a",
}

[scripts.setup.mode_b]
command = ["cargo", "tool", "run"]
env = {
    TOOL_MODE = "b",
}

[[profile.default.scripts]]
filter = "binary_id(example::integration_a)"
setup = ["mode_a"]

[[profile.default.scripts]]
filter = "binary_id(example::integration_b)"
setup = ["mode_b"]
```

I am currently working around this issue by creating platform specific scripts (i.e. `.sh` and `.bat`) to pass environment variables to the underlying program whose implementation I don't have control over. If the mechanism exists to define and pass environment variables to the program directly from the config, those platform specific script wrappers could be completely avoided.

Depending on my time availability I may be able take a stab at this if help is wanted. My assumption is that the relevant structs (if above config structure is used it should be `SetupScriptConfig`) will need to include this new field, implement the deserializer and that `SetupScriptCommand::new()` will need to apply the defined environment variables to the command before the `CARGO_*` and `NEXTEST_*` to avoid the possibility to overwrite those via this mechanism. Naturally write some tests too to make sure this all works. I am just assuming how this might be done given a relatively cursory look at the code base (which is to say the code is very well organized along with good cohesive commits/issues that allow me to home into the relevant bits).
