### ISSUE TITLE
Tracking issue for reuse build options

### ISSUE THREAD

**Issue by sunshowers** [nextest-rs/nextest#98]
cargo-nextest 0.9.10 introduces experimental support for reusing the build across machines and invocations. This issue tracks stabilizing this option:
* [x] How does this interact with #82?
* [x] Verify option names.
* [x] Ensure that the "cargo present on destination" and "cargo not present on destination" scenarios both work well.
* [x] Is the current path remapping support sufficient?

cc @Guiguiprim

**Comment by Guiguiprim** [comment]
So I discovered a current limitation that might need some work.

```sh
# build machine
> cargo nextest list --list-type binaries-only --message-format json > binaries.json
# target machine
> cargo-nextest nextest <all reuse build args> --workspace -p some_package -j1
> cargo-nextest nextest <all reuse build args> --workspace --exclude some_package
```

This doesn't work as expected, during tests run, the test are not filtered base on package (as they were all built).

**Comment by sunshowers** [comment]
@Guiguiprim Good catch! I think we should do two things:
1. Make all the cargo options mutually exclusive with `--binaries-metadata`.
2. Add a way to do post-build filtering by package name. This is useful even in the regular case because of feature unification concerns.

I think 2 should probably use a DSL similar to the one in https://github.com/nextest-rs/nextest/issues/101#issuecomment-1063312776. I realize we're pushing a lot to DSLs, but I think it's important to achieve the orthogonality rather than adding a mess of options.

**Comment by Guiguiprim** [comment]
1. Should be easy to do. I might push a PR for it.
2. Sound good and a small challenge to do.

Otherwise this was successfully integrated in CI !

**Comment by sunshowers** [comment]
That's awesome, thanks for the news and also continuing to work on this!

re 1 we can easily make that happen before 2 (which is quite a bit harder).

BTW when you're ready to do 2 let's discuss the design in a separate PR. I'm imagining a `-E, `--expr-filter` expression-based filter.

**Comment by Guiguiprim** [comment]
For readers:
- Improving conflicting arguments handling was fixed: https://github.com/nextest-rs/nextest/pull/116
- filtering is being worked here: https://github.com/nextest-rs/nextest/pull/117

**Comment by sunshowers** [comment]
@Guiguiprim I think to support #82 we need to rename the `--binaries-dir-remap` to `--target-dir-remap`, and preserve the directory structure within `target` in the archive. I'll recommend just archiving all of `target` for now, and we can add commands to create and extract a more specific archive later.

**Comment by sunshowers** [comment]
Doing the above in #120.

**Comment by sunshowers** [comment]
cargo-nextest 0.9.12 switches to `--target-dir-remap` ([docs](https://github.com/nextest-rs/nextest/blob/978fc3dcf85ed393809a6f9df6b4cabaa1de4d29/site/src/book/reusing-builds.md#example-cross-compilation)).

**Comment by sunshowers** [comment]
Pretty happy with this -- I think the only thing that's left is to write integration tests for the two cases, cargo-at-destination and cargo-not-present-at-destination. This can likely be done by uploading artifacts to the job:
* the cargo-nextest binary
* the target directory

then downloading them on the other end.

**Comment by sunshowers** [comment]
This is now ready as cargo-nextest 0.9.13, with:
* docs at https://nexte.st/book/reusing-builds.html
* example at https://github.com/nextest-rs/reuse-build-partition-example.
